// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/flex/lexer.flex

import compilerTools.Token;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Lexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\36\u0200\1\u0300\1\u0400\266\u0200\10\u0500\u1020\u0200";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\0\1\5\3\0\1\6\1\0\1\7\1\10\1\11"+
    "\1\12\1\13\1\12\1\14\1\15\1\16\11\17\1\0"+
    "\1\20\1\6\1\21\1\6\2\0\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\33\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\33\1\50\1\33\1\51"+
    "\1\0\1\52\1\0\1\33\1\0\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\33\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\33\1\50\1\33\1\53"+
    "\1\6\1\54\7\0\1\3\73\0\1\33\7\0\1\33"+
    "\3\0\1\33\3\0\1\33\1\0\1\33\6\0\1\33"+
    "\1\0\1\33\4\0\1\33\7\0\1\33\3\0\1\33"+
    "\3\0\1\33\1\0\1\33\6\0\1\33\1\0\1\33"+
    "\63\0\2\55\115\0\1\56\u01a8\0\2\3\u0100\0\1\57"+
    "\325\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\7\2\12\1\13\1\14\20\15\1\16"+
    "\1\17\1\20\1\21\2\1\1\0\1\2\10\15\1\22"+
    "\14\15\1\22\4\0\6\15\1\0\1\15\1\23\2\15"+
    "\1\0\4\15\1\0\4\15\1\0\1\15\1\0\1\23"+
    "\2\0\1\2\4\15\1\0\2\15\1\0\4\15\1\0"+
    "\2\15\1\0\1\15\1\0\2\15\1\0\1\15\2\24"+
    "\2\15";

  private static int [] zzUnpackAction() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\60\0\60\0\140\0\60\0\60\0\60\0\60"+
    "\0\60\0\60\0\60\0\220\0\60\0\300\0\60\0\360"+
    "\0\u0120\0\u0150\0\u0180\0\u01b0\0\u01e0\0\u0210\0\u0240\0\u0270"+
    "\0\u02a0\0\u02d0\0\u0300\0\u0330\0\u0360\0\u0390\0\u03c0\0\u03f0"+
    "\0\60\0\60\0\60\0\60\0\u0420\0\u0450\0\u0480\0\u04b0"+
    "\0\u04e0\0\u0510\0\u0540\0\u0570\0\u05a0\0\u05d0\0\u0600\0\u0630"+
    "\0\u0120\0\u0660\0\u0690\0\u06c0\0\u06f0\0\u0720\0\u0750\0\u0780"+
    "\0\u07b0\0\u07e0\0\u0810\0\u0840\0\u0870\0\60\0\u08a0\0\u08d0"+
    "\0\u0900\0\u0930\0\u0960\0\u0990\0\u09c0\0\u09f0\0\u0a20\0\u0a50"+
    "\0\u0a80\0\u0ab0\0\u0120\0\u0ae0\0\u0b10\0\u0b40\0\u0b70\0\u0ba0"+
    "\0\u0bd0\0\u0c00\0\u0c30\0\u0c60\0\u0c90\0\u0cc0\0\u0cf0\0\u0d20"+
    "\0\u0d50\0\u0d80\0\60\0\u0db0\0\u0de0\0\u0900\0\u0e10\0\u0e40"+
    "\0\u0e70\0\u0ea0\0\u0ed0\0\u0f00\0\u0f30\0\u0f60\0\u0f90\0\u0fc0"+
    "\0\u0ff0\0\u1020\0\u1050\0\u1080\0\u10b0\0\u10e0\0\u1110\0\u1140"+
    "\0\u1170\0\u11a0\0\u11d0\0\u1200\0\u0120\0\60\0\u1230\0\u1260";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\2\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\2\21\1\27"+
    "\2\21\1\30\1\31\1\32\1\21\1\33\1\34\1\35"+
    "\1\36\1\21\1\37\1\40\1\21\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\2\62\0\1\3\66\0\1\47"+
    "\3\0\1\50\60\0\2\16\61\0\1\6\54\0\2\21"+
    "\2\0\27\21\25\0\2\21\2\0\16\21\1\51\1\21"+
    "\1\52\5\21\1\53\25\0\2\21\2\0\7\21\1\54"+
    "\17\21\25\0\2\21\2\0\16\21\1\55\10\21\25\0"+
    "\2\21\2\0\13\21\1\56\13\21\25\0\2\21\2\0"+
    "\1\25\12\21\1\57\2\21\1\60\10\21\25\0\2\21"+
    "\2\0\5\21\1\61\7\21\1\62\11\21\25\0\2\21"+
    "\2\0\16\21\1\63\10\21\25\0\2\21\2\0\1\64"+
    "\26\21\25\0\2\21\2\0\23\21\1\65\3\21\25\0"+
    "\2\21\2\0\1\66\17\21\1\67\2\21\1\70\3\21"+
    "\25\0\2\21\2\0\4\21\1\71\22\21\25\0\2\21"+
    "\2\0\7\21\1\72\17\21\25\0\2\21\2\0\20\21"+
    "\1\73\6\21\25\0\2\21\2\0\16\21\1\74\10\21"+
    "\25\0\2\21\2\0\7\21\1\75\17\21\36\0\1\76"+
    "\7\0\1\77\51\0\1\100\26\0\11\101\1\102\46\101"+
    "\2\50\1\3\1\50\1\4\53\50\16\0\2\21\2\0"+
    "\16\21\1\103\10\21\25\0\2\21\2\0\4\21\1\104"+
    "\22\21\25\0\2\21\2\0\22\21\1\105\4\21\25\0"+
    "\2\21\2\0\1\106\26\21\25\0\2\21\2\0\23\21"+
    "\1\107\3\21\25\0\2\21\2\0\21\21\1\110\5\21"+
    "\5\0\1\111\17\0\2\21\2\0\16\21\1\112\10\21"+
    "\25\0\2\21\2\0\20\21\1\61\6\21\25\0\2\21"+
    "\2\0\22\21\1\113\4\21\25\0\2\21\2\0\15\21"+
    "\1\114\11\21\25\0\2\21\2\0\10\21\1\115\16\21"+
    "\4\0\1\116\20\0\2\21\2\0\13\21\1\117\13\21"+
    "\25\0\2\21\2\0\2\21\1\120\24\21\25\0\2\21"+
    "\2\0\10\21\1\121\5\21\1\122\10\21\4\0\1\123"+
    "\20\0\2\21\2\0\1\21\1\124\25\21\25\0\2\21"+
    "\2\0\22\21\1\125\4\21\25\0\2\21\2\0\16\21"+
    "\1\126\10\21\25\0\2\21\2\0\23\21\1\110\3\21"+
    "\25\0\2\21\2\0\10\21\1\127\16\21\4\0\1\130"+
    "\20\0\2\21\2\0\10\21\1\131\16\21\4\0\1\132"+
    "\46\0\1\133\53\0\1\134\17\0\11\101\1\135\57\101"+
    "\1\135\3\101\1\136\42\101\16\0\2\21\2\0\13\21"+
    "\1\137\13\21\25\0\2\21\2\0\1\140\26\21\25\0"+
    "\2\21\2\0\4\21\1\113\22\21\25\0\2\21\2\0"+
    "\20\21\1\113\6\21\25\0\2\21\2\0\1\21\1\141"+
    "\25\21\25\0\2\21\2\0\4\21\1\61\22\21\35\0"+
    "\1\76\47\0\2\21\2\0\1\62\26\21\25\0\2\21"+
    "\2\0\6\21\1\113\20\21\25\0\2\21\2\0\15\21"+
    "\1\61\11\21\46\0\1\76\36\0\2\21\2\0\13\21"+
    "\1\61\13\21\25\0\2\21\2\0\12\21\1\142\14\21"+
    "\6\0\1\143\16\0\2\21\2\0\24\21\1\144\2\21"+
    "\25\0\2\21\2\0\22\21\1\145\4\21\55\0\1\146"+
    "\27\0\2\21\2\0\13\21\1\147\13\21\25\0\2\21"+
    "\2\0\23\21\1\150\3\21\25\0\2\21\2\0\20\21"+
    "\1\62\6\21\25\0\2\21\2\0\3\21\1\113\23\21"+
    "\34\0\1\133\50\0\2\21\2\0\13\21\1\110\13\21"+
    "\44\0\1\111\64\0\1\77\15\0\11\101\1\135\3\101"+
    "\1\3\42\101\16\0\2\21\2\0\4\21\1\151\22\21"+
    "\25\0\2\21\2\0\12\21\1\61\14\21\6\0\1\76"+
    "\16\0\2\21\2\0\13\21\1\105\13\21\25\0\2\21"+
    "\2\0\1\152\26\21\31\0\1\153\53\0\2\21\2\0"+
    "\1\154\26\21\25\0\2\21\2\0\4\21\1\155\22\21"+
    "\31\0\1\156\53\0\2\21\2\0\10\21\1\157\16\21"+
    "\4\0\1\160\20\0\2\21\2\0\20\21\1\115\6\21"+
    "\25\0\2\21\2\0\1\161\26\21\25\0\2\21\2\0"+
    "\6\21\1\162\20\21\37\0\1\163\45\0\2\21\2\0"+
    "\22\21\1\162\4\21\25\0\2\21\2\0\2\21\1\164"+
    "\24\21\53\0\1\163\31\0\2\21\2\0\2\21\1\165"+
    "\24\21\33\0\1\166\51\0\2\21\2\0\15\21\1\113"+
    "\11\21\25\0\2\21\2\0\4\21\1\165\22\21\35\0"+
    "\1\166\47\0\2\21\2\0\22\21\1\167\4\21\25\0"+
    "\2\21\2\0\4\21\1\170\22\21\25\0\2\21\2\0"+
    "\3\21\1\165\23\21\7\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4752];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\1\1\7\11\1\1\1\11\1\1\1\11"+
    "\21\1\4\11\2\1\1\0\26\1\1\11\4\0\6\1"+
    "\1\0\4\1\1\0\4\1\1\0\4\1\1\0\1\1"+
    "\1\0\1\11\2\0\5\1\1\0\2\1\1\0\4\1"+
    "\1\0\2\1\1\0\1\1\1\0\2\1\1\0\2\1"+
    "\1\11\2\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[120];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    private Token token(String lexeme, String lexicalComp, int line, int column){
        return new Token(lexeme, lexicalComp, line+1, column+1);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(yytext(), "ERROR", yyline, yycolumn);
            }
            // fall through
          case 21: break;
          case 2:
            { /*Ignorar*/
            }
            // fall through
          case 22: break;
          case 3:
            { return token(yytext(), "COMILLAS", yyline, yycolumn);
            }
            // fall through
          case 23: break;
          case 4:
            { return token(yytext(), "OP_Logico", yyline, yycolumn);
            }
            // fall through
          case 24: break;
          case 5:
            { return token(yytext(), "PARENTESIS_ABIERTO", yyline, yycolumn);
            }
            // fall through
          case 25: break;
          case 6:
            { return token(yytext(), "PARENTESIS_CERRADO", yyline, yycolumn);
            }
            // fall through
          case 26: break;
          case 7:
            { return token(yytext(), "OP_Aritmetico", yyline, yycolumn);
            }
            // fall through
          case 27: break;
          case 8:
            { return token(yytext(), "COMA", yyline, yycolumn);
            }
            // fall through
          case 28: break;
          case 9:
            { return token(yytext(), "PUNTO", yyline, yycolumn);
            }
            // fall through
          case 29: break;
          case 10:
            { return token(yytext(), "Numero", yyline, yycolumn);
            }
            // fall through
          case 30: break;
          case 11:
            { return token(yytext(), "PUNTO_Y_COMA", yyline, yycolumn);
            }
            // fall through
          case 31: break;
          case 12:
            { return token(yytext(), "ASIGNACION", yyline, yycolumn);
            }
            // fall through
          case 32: break;
          case 13:
            { return token(yytext(), "Identificador", yyline, yycolumn);
            }
            // fall through
          case 33: break;
          case 14:
            { return token(yytext(), "CORCHETE_ABIERTO", yyline, yycolumn);
            }
            // fall through
          case 34: break;
          case 15:
            { return token(yytext(), "CORCHETE_CERRADO", yyline, yycolumn);
            }
            // fall through
          case 35: break;
          case 16:
            { return token(yytext(), "LLAVE_ABIERTA", yyline, yycolumn);
            }
            // fall through
          case 36: break;
          case 17:
            { return token(yytext(), "LLAVE_CERRADA", yyline, yycolumn);
            }
            // fall through
          case 37: break;
          case 18:
            { return token(yytext(), "Palabra_Reservada", yyline, yycolumn);
            }
            // fall through
          case 38: break;
          case 19:
            { return token(yytext(), "Tipo_de_dato", yyline, yycolumn);
            }
            // fall through
          case 39: break;
          case 20:
            { return token(yytext(), "Modificador_de_Acceso", yyline, yycolumn);
            }
            // fall through
          case 40: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
